# Generated by Django 4.2.18 on 2025-01-18 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='developer',
            name='data',
            field=models.JSONField(default=1),
            preserve_default=False,
        ),
    ]
