# Generated by Django 4.2.18 on 2025-01-18 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_choice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='developer',
            name='count',
        ),
    ]
